channels:
  # Define conda channels here.
  - conda-forge

dependencies:
  # Define conda packages here.
  # If available, always prefer the conda version of a package, installation will be faster and more efficient.
  # https://anaconda.org/search
  - python==3.12.10
  - proglog==0.1.10
  - watchdog==6.0.0

  - pip:
      - moviepy==2.1.2
      - flet==0.27.6

  # Define pip packages here.
  # https://pypi.org/
