name: ARM-Only Build and Release
on:
  push:
    tags:
      - "v*" # Run workflow on version tags, e.g. v1.0.0
jobs:
  build:
    name: Build for ARM
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python 3.12
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"
          architecture: arm64
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
        shell: bash
      - name: Build package
        run: |
          echo "Building for macOS ARM"
          pyinstaller main.py --name audio_silence_splitter-darwin-arm
        shell: bash
      - name: Upload build artifacts
        uses: actions/upload-artifact@v4
        with:
          name: darwin-arm-build
          path: dist/*
  release:
    name: Create Release
    needs: build
    if: startsWith(github.ref, 'refs/tags/v')
    runs-on: ubuntu-latest
    steps:
      - name: Download all artifacts
        uses: actions/download-artifact@v4
        with:
          path: ./artifacts
      - name: Create GitHub Release
        id: create_release
        uses: softprops/action-gh-release@v2
        with:
          files: |
            artifacts/**/*
          draft: false
          prerelease: false
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
